# Generated by Django 3.2.7 on 2021-09-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_skilltag_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Место работы')),
                ('description', models.TextField(verbose_name='Чем занимался')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название проекта'),
        ),
    ]
