# Generated by Django 3.2.7 on 2021-09-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Место работы'),
        ),
    ]
