# Generated by Django 3.2.7 on 2021-09-04 01:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_work_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2021, 9, 4, 1, 35, 1, 60123, tzinfo=utc), verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='work',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 9, 4, 1, 35, 1, 60086, tzinfo=utc), verbose_name='Дата начала работы'),
        ),
    ]
