# Generated by Django 3.2.7 on 2021-09-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20210904_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='by_today',
            field=models.BooleanField(default=False, verbose_name='По сегодняшний день'),
        ),
    ]
