# Generated by Django 3.2.7 on 2021-09-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_auto_20210920_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(max_length=120, null=True, verbose_name='Роль'),
        ),
    ]
